# Generated by Django 5.1.1 on 2024-11-18 20:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(choices=[('text/markdown', 'Markdown'), ('text/plain', 'UTF-8'), ('image/jpeg', 'jpeg'), ('application/base64', 'jpeg/png'), ('image/png;base64', 'png'), ('image/jpeg;base64', 'jpeg')], max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'PUBLIC'), ('friend-only', 'FRIENDS'), ('unlisted', 'UNLISTED')], default='public', max_length=11)),
                ('type', models.CharField(default='post', editable=False, max_length=10)),
                ('fqid', models.URLField(blank=True, null=True)),
                ('serial', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('github_event_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='author.author')),
            ],
        ),
    ]
