# Generated by Django 5.1.1 on 2024-11-04 05:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(choices=[('text/markdown', 'Markdown'), ('image/jpeg', 'JPEG')], max_length=50)),
                ('image_content', models.ImageField(blank=True, null=True, upload_to='post_pics')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('friend-only', 'Friend Only'), ('unlisted', 'Unlisted')], default='public', max_length=11)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='author.author')),
            ],
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('friend-only', 'Friend Only')], default='public', max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='post.post')),
                ('reposted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='author.author')),
            ],
        ),
    ]
