# Generated by Django 5.1.1 on 2024-10-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repost',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
