# Generated by Django 5.1.1 on 2024-11-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'PUBLIC'), ('friends', 'FRIENDS'), ('unlisted', 'UNLISTED'), ('deleted', 'DELETED')], default='public', max_length=11),
        ),
    ]
