# Generated by Django 5.1.1 on 2024-10-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_repost_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='repost',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('friend-only', 'Friend Only')], default='public', max_length=20),
        ),
    ]
