# Generated by Django 5.1.1 on 2024-10-26 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_repost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repost',
            old_name='author',
            new_name='resposted_by',
        ),
    ]
