# Generated by Django 5.1.1 on 2024-10-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_author_repost_resposted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repost',
            old_name='resposted_by',
            new_name='reposted_by',
        ),
    ]
