# Generated by Django 5.1.1 on 2024-12-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_post_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fqid',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='github_event_id',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
