# Generated by Django 5.1.1 on 2024-11-01 03:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0003_alter_author_created_at_alter_author_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_content', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('friend-only', 'Friend Only'), ('unlisted', 'Unlisted')], default='public', max_length=11)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_posts', to='author.author')),
            ],
        ),
    ]
