# Generated by Django 5.1.1 on 2024-11-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='content_type',
            field=models.TextField(default='image/jpeg'),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='image_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
