# Generated by Django 5.1.1 on 2024-11-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
