# Generated by Django 5.1.1 on 2024-10-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='pending',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(default='public', max_length=10),
        ),
    ]
