# Generated by Django 5.1.1 on 2024-10-18 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_follow_pending_alter_post_visibility'),
        ('service', '0002_post_is_deleted'),
    ]

    operations = [
    ]
