# Generated by Django 5.1.1 on 2024-10-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_post_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friend-only', 'Friend Only'), ('unlisted', 'Unlisted')], default='public', max_length=11),
        ),
    ]
