# Generated by Django 5.1.1 on 2024-10-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_merge_20241018_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friend-only', 'Friend Only'), ('unlisted', 'Unlisted')], default='public', max_length=11),
        ),
    ]
