# Generated by Django 5.1.1 on 2024-10-20 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_post_visibility'),
        ('service', '0004_alter_post_visibility'),
    ]

    operations = [
    ]
