# Generated by Django 5.1.1 on 2024-11-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='username',
        ),
    ]
