# Generated by Django 5.1.1 on 2024-11-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
