# Generated by Django 5.1.1 on 2024-11-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_remove_author_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
