# Generated by Django 5.1.1 on 2024-11-04 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_github_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='followers',
        ),
    ]
