# Generated by Django 5.1.1 on 2024-11-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='fqid',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='host',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='type',
            field=models.CharField(default='author', editable=False, max_length=10),
        ),
    ]
