# Generated by Django 5.1.1 on 2024-11-04 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_author_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='followers',
        ),
    ]
