# Generated by Django 5.1.1 on 2024-12-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='fqid',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
