# Generated by Django 5.1.1 on 2024-12-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_alter_like_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='fqid',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='object',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
